language: node_js
branches:
  except:
    - latest
node_js:
  - '0.10'
  - '0.12'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
  - gem install cucumber
  - gem install aruba -v 0.7.4
script:
  - npm test
  - cucumber -t ~@wip
  - ./bin/product-csv-sync import --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --csv data/simple-import.csv --suppressMissingHeaderWarning
  - ./bin/product-csv-sync template --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --out data/template_sample.csv --all
  - ./bin/product-csv-sync export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --template data/template_sample.csv --out data/exported.csv
  - ./bin/product-csv-sync state --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --changeTo delete --forceDelete
branches:
  except:
    - /^v[0-9]\.[0-9]\.[0-9]$/
notifications:
  hipchat:
    rooms:
      secure: KgryNM2IN5oc407jAiNxKFnKohyOccHdcJ7Tb+RamcuMOGj6xftMMnTwDvlqLGsXiaoMNQh44E5DGiHiBtrwPx7x1Qn7uXWD4lYxCQL3Tbd0DnsW+1PyFmOR6X1N7qcYKRtq3xwS+lW0WuTr1HkbXZ8pZpKR2/ipLzANQJUITgY=
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
env:
  global:
    - secure: GStZeS8lCr5AbseJ7HrKwAA9pw6UbkVN0l6vZynKgbuYQSQmWBNuLrtWi08ykkpKMKNsHIlh6+wPSgcxiJ7kX7E+o1EA4VJPqKqzi2ITmri4jHukQAMD0RvcD62wBJJi7juZiMd40CsXklOPFCYy/x7jBupw0L8bV8OVGq2JKNI=
    - secure: VqPJV184aJL2aCJB/KH953YMSRHJhWcYS9ySn6TLbZI6jDD+ul/DIhk0hlMNp1JlkTAuXocwJWZH00R1WUexamEdGO8l/Gv06soNFSKM0klsQxkNvmISfTqSXWZGckOtqScTuOzStCEXk/uT6Vo5cycsxYkZBTPBXEn4J5SB0po=
    - secure: szr8OjiKyPinz/k8sFmutIURoMEI75KeVA7h6hgVb03zxCfLbPP991TPwdfNyqIaBWucjI11yY2AeDJsK7cmaYdYRHktFGoRdiLAU0sCKfHuyxIXPSHYq4krY0rIyCMtpsYad/hfZ5yNTX5B6l7gTxTjFpPmCKXaDRYwdk57uB4=
sudo: false
