language: node_js
branches:
  except:
    - latest
node_js:
  - '8'
  - '6'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
  - gem install cucumber
  - gem install aruba -v 0.7.4
script:
  - npm test
  - cucumber -t ~@wip
  - cat data/simple-import.csv | ./bin/product-csv-sync import --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --suppressMissingHeaderWarning --matchBy sku
  - cat data/template_sample.csv | ./bin/product-csv-sync export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET}
  - ./bin/product-csv-sync import --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --csv data/simple-import.csv --suppressMissingHeaderWarning --matchBy sku
  - ./bin/product-csv-sync template --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --out data/template_sample.csv --all
  - ./bin/product-csv-sync export --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --template data/template_sample.csv --out data/exported.csv
  - ./bin/product-csv-sync state --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET} --changeTo delete --forceDelete
branches:
  except:
    - /^v[0-9]\.[0-9]\.[0-9]$/
notifications:
  hipchat:
    rooms:
      secure: KgryNM2IN5oc407jAiNxKFnKohyOccHdcJ7Tb+RamcuMOGj6xftMMnTwDvlqLGsXiaoMNQh44E5DGiHiBtrwPx7x1Qn7uXWD4lYxCQL3Tbd0DnsW+1PyFmOR6X1N7qcYKRtq3xwS+lW0WuTr1HkbXZ8pZpKR2/ipLzANQJUITgY=
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
env:
  global:
    - secure: adpy37rxbdN5Z3PVmWfDZupr49PJogs1yE0/ATaK1oEdji1Sd4Zqmlsh+AfaXR7TzmdY/77EuKYbFJ0clK0QisV0ISyiKGM04EVyi0gAiV52k6LLMMs9LNmcTCm6B2oapQ7Jty7vk0jzi9XgVTicU65yx4YdKtn6Gkj+ygXbpCE=
    - secure: AQsFzgFzDW6bbz71OmQIZlQzX3N9/6GEm4tJmc45WZZ+PCE/GWePA3SFiRnBC2egTO+6ZiiUFmg9aDwiFLtLa4z6kDlzNQWZy4Fg1hMXKXz8FVvLzaW3X6st/MC6YUNpuJO1Zr5ghtgt6IMhrMpqCeMxqjdCTQjOIwI1y9FORl0=
    - secure: YfkeSyk3cJr7G4x0mg5yYjCtJQUE4lKmGt7HFAFxxqGZ5KHcXYu43i1RrMV73X+LeqRzGSxDWaXcssocCGs6Iv8nGpiytlmC4LdRizz1cLq+nqVgizJAJjv6NL71p1wBjuD0ZsWaXbAdpy5ddBDxcwVirOiLfe8wjU4gQAiqTtg=
sudo: false
